version: "3.9"
services:
  master:
      build: .
      dockerfile: Dockerfile_master
      ports:
       - "8880:8880"
  slave:
    build: .
    dockerfile: Dockerfile_slave
    ports:
      - "8881:8881"
